export const FETCHING_DATA = 'FETCHING_DATA'
export const FETCHING_DATA_SUCCESS = 'FETCHING_DATA_SUCCESS'
export const FETCHING_DATA_FAILURE = 'FETCHING_DATA_FAILURE'


export const CREATING_IMG_ANNOTATION = 'CREATING_IMG_ANNOTATION';
export const CREATING_IMG_ANNOTATION_SUCCESS = 'CREATING_IMG_ANNOTATION_SUCCESS';
export const CREATING_IMG_ANNOTATION_FAILURE = 'CREATING_IMG_ANNOTATION_FAILURE';

export const FETCH_ANNOTATIONS = 'FETCH_ANNOTATIONS';
export const FETCH_ANNOTATIONS_SUCCESS = 'FETCH_ANNOTATIONS_SUCCESS';
export const FETCH_ANNOTATIONS_FAILURE = 'FETCH_ANNOTATIONS_FAILURE';