export const FETCHING_DATA = 'FETCHING_DATA'
export const FETCHING_DATA_SUCCESS = 'FETCHING_DATA_SUCCESS'
export const FETCHING_DATA_FAILURE = 'FETCHING_DATA_FAILURE'

export const CREATE_CONTENT = 'CREATE_CONTENT';
export const CREATE_CONTENT_SUCCESS = 'CREATE_CONTENT_SUCCESS';
export const CREATE_CONTENT_FAILURE = 'CREATE_CONTENT_FAILURE';






export const CREATING_IMG_ANNOTATION = 'CREATING_IMG_ANNOTATION';
export const CREATING_IMG_ANNOTATION_SUCCESS = 'CREATING_IMG_ANNOTATION_SUCCESS';
export const CREATING_IMG_ANNOTATION_FAILURE = 'CREATING_IMG_ANNOTATION_FAILURE';

export const FETCH_ANNOTATIONS = 'FETCH_ANNOTATIONS';
export const FETCH_ANNOTATIONS_SUCCESS = 'FETCH_ANNOTATIONS_SUCCESS';
export const FETCH_ANNOTATIONS_FAILURE = 'FETCH_ANNOTATIONS_FAILURE';

export const LOGIN_TO_SYSTEM = 'LOGIN_TO_SYSTEM';
export const LOGIN_TO_SYSTEM_SUCCESS = 'LOGIN_TO_SYSTEM_SUCCESS';
export const LOGIN_TO_SYSTEM_FAILURE = 'LOGIN_TO_SYSTEM_FAILURE';

export const REGISTER_TO_SYSTEM = 'REGISTER_TO_SYSTEM';
export const REGISTER_TO_SYSTEM_SUCCESS = 'REGISTER_TO_SYSTEM_SUCCESS';
export const REGISTER_TO_SYSTEM_FAILURE = 'REGISTER_TO_SYSTEM_FAILURE';

export const CREATING_TEXT_ANNOTATION = 'CREATING_TEXT_ANNOTATION';
export const CREATING_TEXT_ANNOTATION_SUCCESS = 'CREATING_TEXT_ANNOTATION_SUCCESS';
export const CREATING_TEXT_ANNOTATION_FAILURE =  'CREATING_TEXT_ANNOTATION_FAILURE';

export const FETCH_CONTENTS = 'FETCH_CONTENTS';
export const FETCH_CONTENTS_SUCCESS = 'FETCH_CONTENTS_SUCCESS';
export const FETCH_CONTENTS_FAILURE = 'FETCH_CONTENTS_FAILURE';

export const CREATE_IMAGE_CONTENT = 'CREATE_IMAGE_CONTENT';
export const CREATE_IMAGE_CONTENT_SUCCESS = 'CREATE_IMAGE_CONTENT_SUCCESS';
export const CREATE_IMAGE_CONTENT_FAILURE = 'CREATE_IMAGE_CONTENT_FAILURE';

export const CREATE_SEMANTIC_ANNOTATION = 'CREATE_SEMANTIC_ANNOTATION';
export const CREATE_SEMANTIC_ANNOTATION_SUCCESS = 'CREATE_SEMANTIC_ANNOTATION_SUCCESS';
export const CREATE_SEMANTIC_ANNOTATION_FAILURE = 'CREATE_SEMANTIC_ANNOTATION_FAILURE';

export const FETCH_SEMANTIC_BODIES = 'FETCH_SEMANTIC_BODIES';
export const FETCH_SEMANTIC_BODIES_SUCCESS = 'FETCH_SEMANTIC_BODIES_SUCCESS';
export const FETCH_SEMANTIC_BODIES_FAILURE = 'FETCH_SEMANTIC_BODIES_FAILURE';