# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

source 'https://github.com/CocoaPods/Specs.git'


target 'LivingHistory' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for LivingHistory

  pod 'GooglePlaces'
  pod 'GoogleMaps'
  pod 'GooglePlacePicker'

  target 'LivingHistoryTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'LivingHistory-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for LivingHistory-tvOS

  target 'LivingHistory-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
